# Generated by Django 5.1 on 2024-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('level', models.CharField(default=True, max_length=50)),
                ('birth_day', models.DateField(max_length=10)),
                ('sex', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=20)),
            ],
        ),
    ]
