# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('1ère', '1ère'), ('2nde', '2nde'), ('3ème', '3ème'), ('4ème', '4ème'), ('5ème', '5ème')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('h', 'homme'), ('f', 'femme')], max_length=10),
        ),
    ]
