# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('h', 'homme'), ('f', 'femme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'maths'), ('SVT', 'svt'), ('PHYSIQUE', 'physique'), ('English', 'English'), ('Frensh', 'Frensh')], max_length=10),
        ),
    ]
